// apps/angular-app/src/app/components/carrinho-modal/carrinho-modal.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ItemCarrinho, UsuarioLogado } from '../../models/types';
import { PedidoService } from '../../services/pedido.service';
import { ToastService } from '../../services/toast.service';

const WHATSAPP_NUMBER = '559999999999';
const APP_NAME = 'Cozinha Ramos';

@Component({
  selector: 'app-carrinho-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './carrinho-modal.html',
  styleUrl: './carrinho-modal.css'
})
export class CarrinhoModalComponent {
  @Input() itens: ItemCarrinho[] = [];
  @Input() usuario: UsuarioLogado | null = null;
  @Output() fechar = new EventEmitter<void>();
  @Output() remover = new EventEmitter<string>();
  @Output() atualizarQtd = new EventEmitter<{ id: string; delta: number }>();
  @Output() finalizar = new EventEmitter<void>();

  private moneyFormatter = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });

  constructor(private pedidoService: PedidoService, private toast: ToastService) {}

  get total(): number {
    return this.itens.reduce((acc, item) => acc + item.preco * item.quantidade, 0);
  }

  formatarPreco(valor: number): string {
    return this.moneyFormatter.format(valor);
  }

  handleAtualizarQtd(item: ItemCarrinho, delta: number) {
    if (item.quantidade + delta <= 0) {
      this.remover.emit(item.id);
    } else {
      this.atualizarQtd.emit({ id: item.id, delta });
    }
  }

  async finalizarPedido() {
    if (!this.usuario) {
      alert('Você precisa estar logado para finalizar o pedido.');
      return;
    }

    this.pedidoService.criarPedido(this.usuario.id, this.itens, this.total).subscribe({
      next: () => {
        let mensagem = `*Novo Pedido - ${APP_NAME}*\nCliente: ${this.usuario!.nome}\n\n`;
        this.itens.forEach(item => {
          mensagem += `${item.quantidade}x ${item.nome} - ${this.moneyFormatter.format(item.preco * item.quantidade)}\n`;
        });
        mensagem += `\n*Total: ${this.moneyFormatter.format(this.total)}*`;

        const url = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(mensagem)}`;
        window.open(url, '_blank', 'noopener,noreferrer');
        this.finalizar.emit();
      },
      error: () => {
        alert('Houve um erro ao registrar seu pedido no sistema. Mas você ainda pode tentar pelo WhatsApp.');
      }
    });
  }
}

// apps/react-app/src/components/CarrinhoModal/CarrinhoModal.tsx
import axios from 'axios';
import { Icons } from '../Icons';
import type { ItemCarrinho } from '@shared/types/Produto';
import { CONFIG } from '@shared/constants/config';
import './CarrinhoModal.css';

interface CarrinhoModalProps {
  itens: ItemCarrinho[];
  usuario: { id: string; nome: string } | null;
  onFechar: () => void;
  onRemover: (id: string) => void;
  onAtualizarQtd: (id: string, delta: number) => void;
  onFinalizar: () => void;
}

export default function CarrinhoModal({ 
  itens, 
  usuario,
  onFechar, 
  onRemover, 
  onAtualizarQtd, 
  onFinalizar 
}: CarrinhoModalProps) {
  
  const moneyFormatter = new Intl.NumberFormat(CONFIG.CURRENCY.LOCALE, {
    style: 'currency',
    currency: CONFIG.CURRENCY.CODE,
  });

  const total = itens.reduce((acc, item) => acc + item.preco * item.quantidade, 0);

  const finalizarPedido = async () => {
    if (!usuario) {
      alert("Você precisa estar logado para finalizar o pedido.");
      return;
    }

    try {
      const payload = {
        usuarioId: usuario.id,
        itens: itens.map(i => ({ 
          produtoId: i.id, 
          nome: i.nome, 
          quantidade: i.quantidade, 
          preco: i.preco 
        })),
        total: total
      };
      
      await axios.post(`${CONFIG.API_URL}/pedidos`, payload);

      let mensagem = `*Novo Pedido - ${CONFIG.APP.NAME}*\n`;
      mensagem += `Cliente: ${usuario.nome}\n\n`;
      
      itens.forEach(item => {
        const subtotal = moneyFormatter.format(item.preco * item.quantidade);
        mensagem += `${item.quantidade}x ${item.nome} - ${subtotal}\n`;
      });

      mensagem += `\n*Total: ${moneyFormatter.format(total)}*`;
      
      const url = `https://wa.me/${CONFIG.CONTACT.WHATSAPP_NUMBER}?text=${encodeURIComponent(mensagem)}`;
      
      window.open(url, '_blank', 'noopener,noreferrer');

      onFinalizar();
      
    } catch (err) {
      console.error("Erro ao salvar pedido:", err);
      alert("Houve um erro ao registrar seu pedido no sistema. Mas você ainda pode tentar pelo WhatsApp.");
    }
  };

  const handleAtualizarQtd = (item: ItemCarrinho, delta: number) => {
    if (item.quantidade + delta <= 0) {
      onRemover(item.id);
    } else {
      onAtualizarQtd(item.id, delta);
    }
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content animate-in slide-in-from-right duration-300">
        <div className="modal-header">
          <h2 className="modal-title">Seu Pedido</h2>
          <button 
            onClick={onFechar} 
            className="btn-close"
            aria-label="Fechar carrinho"
          >
            <Icons.Close size={24} />
          </button>
        </div>

        <div className="cart-items-container">
          {itens.length === 0 ? (
            <div className="text-center mt-10">
              <p className="cart-empty-text mb-4">Seu carrinho está vazio.</p>
              <button 
                onClick={onFechar} 
                className="text-ramos-verde font-bold underline cursor-pointer hover:text-ramos-marrom transition-colors"
              >
                Voltar ao cardápio
              </button>
            </div>
          ) : (
            itens.map(item => (
              <div key={item.id} className="cart-item-card">
                <img 
                  src={item.imagem} 
                  className="cart-item-image" 
                  alt={`Imagem de ${item.nome}`} 
                />
                <div className="cart-item-info">
                  <h4 className="cart-item-name">{item.nome}</h4>
                  <p className="cart-item-price">{moneyFormatter.format(item.preco)}</p>
                  
                  <div className="qty-controls">
                    <button 
                      onClick={() => handleAtualizarQtd(item, -1)}
                      className="btn-qty"
                    >-</button>
                    <span className="qty-display">{item.quantidade}</span>
                    <button 
                      onClick={() => handleAtualizarQtd(item, 1)}
                      className="btn-qty"
                    >+</button>
                  </div>
                </div>
                <button 
                  onClick={() => onRemover(item.id)} 
                  className="btn-remove"
                >
                  <Icons.Trash size={18} />
                </button>
              </div>
            ))
          )}
        </div>

        {itens.length > 0 && (
          <div className="modal-footer">
            <div className="total-container">
              <span>Total:</span>
              <span>{moneyFormatter.format(total)}</span>
            </div>
            <button 
              onClick={finalizarPedido}
              className="btn-checkout"
            >
              <Icons.WhatsApp size={24} />
              Enviar para o WhatsApp
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
