// apps/angular-app/src/app/app.ts
import { Component, OnInit, computed, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthService } from './services/auth.service';
import { ProdutoService } from './services/produto.service';
import { ToastService } from './services/toast.service';
import { HeaderComponent } from './components/header/header';
import { FooterComponent } from './components/footer/footer';
import { CardProdutoComponent } from './components/card-produto/card-produto';
import { CarrinhoModalComponent } from './components/carrinho-modal/carrinho-modal';
import { LoginComponent } from './pages/login/login';
import { ItemCarrinho, Produto, UsuarioLogado } from './models/types';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    HeaderComponent,
    FooterComponent,
    CardProdutoComponent,
    CarrinhoModalComponent,
    LoginComponent
  ],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App implements OnInit {
  private authService = inject(AuthService);
  private produtoService = inject(ProdutoService);
  toastService = inject(ToastService);

  usuario = computed(() => this.authService.usuario());
  produtos = signal<Produto[]>([]);
  carrinho = signal<ItemCarrinho[]>(this.carregarCarrinho());
  isCarrinhoAberto = signal(false);
  isCarregando = signal(true);
  categoriaAtiva = signal('Todos');

  categorias = computed(() => ['Todos', ...new Set(this.produtos().map(p => p.categoria))]);
  totalItens = computed(() => this.carrinho().reduce((acc, i) => acc + i.quantidade, 0));
  produtosFiltrados = computed(() =>
    this.categoriaAtiva() === 'Todos'
      ? this.produtos()
      : this.produtos().filter(p => p.categoria === this.categoriaAtiva())
  );
  skeletons = Array.from({ length: 6 });

  ngOnInit() {
    if (this.usuario()) this.buscarProdutos();
  }

  private carregarCarrinho(): ItemCarrinho[] {
    try {
      const salvo = localStorage.getItem('@CozinhaRamos:carrinho');
      return salvo ? JSON.parse(salvo) : [];
    } catch { return []; }
  }

  private salvarCarrinho() {
    localStorage.setItem('@CozinhaRamos:carrinho', JSON.stringify(this.carrinho()));
  }

  buscarProdutos() {
    this.isCarregando.set(true);
    this.produtoService.getProdutos().subscribe({
      next: (data) => { this.produtos.set(data); this.isCarregando.set(false); },
      error: () => { this.toastService.error('Não foi possível carregar o cardápio.'); this.isCarregando.set(false); }
    });
  }

  handleLoginSuccess(userData: UsuarioLogado) {
    this.authService.salvarUsuario(userData);
    this.toastService.success(`Bem-vindo, ${userData.nome}!`);
    this.buscarProdutos();
  }

  handleSair() {
    this.authService.sair();
    this.toastService.success('Sessão encerrada!');
  }

  adicionarAoCarrinho(produto: Produto) {
    this.carrinho.update(prev => {
      const existe = prev.find(i => i.id === produto.id);
      return existe
        ? prev.map(i => i.id === produto.id ? { ...i, quantidade: i.quantidade + 1 } : i)
        : [...prev, { ...produto, quantidade: 1 }];
    });
    this.salvarCarrinho();
    this.toastService.success(`${produto.nome} adicionado!`);
  }

  removerDoCarrinho(id: string) {
    this.carrinho.update(prev => prev.filter(i => i.id !== id));
    this.salvarCarrinho();
  }

  atualizarQuantidade(event: { id: string; delta: number }) {
    this.carrinho.update(prev =>
      prev.map(i => i.id === event.id ? { ...i, quantidade: i.quantidade + event.delta } : i)
          .filter(i => i.quantidade > 0)
    );
    this.salvarCarrinho();
  }

  limparCarrinho() {
    this.carrinho.set([]);
    this.isCarrinhoAberto.set(false);
    this.salvarCarrinho();
  }
}

// apps/react-app/src/App.tsx
import { useState, useEffect, useMemo } from 'react';
import axios from 'axios';

import Login from './pages/Login';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import CardProduto from './components/CardProduto/CardProduto';
import CarrinhoModal from './components/CarrinhoModal/CarrinhoModal';

import { CONFIG } from '@shared/constants/config';
import type { ItemCarrinho, Produto } from '@shared/types/Produto';

import { Toaster, toast } from 'react-hot-toast';

import './App.css';

interface UsuarioLogado {
  id: string;
  nome: string;
  email: string;
  token?: string;
}

export default function App() {
  const [usuario, setUsuario] = useState<UsuarioLogado | null>(() => {
    const salvo = localStorage.getItem('@CozinhaRamos:usuario');
    return salvo ? JSON.parse(salvo) : null;
  });
  
  const [produtos, setProdutos] = useState<Produto[]>([]);
  const [isCarrinhoAberto, setIsCarrinhoAberto] = useState(false);
  const [isCarregando, setIsCarregando] = useState(true);
  const [categoriaAtiva, setCategoriaAtiva] = useState('Todos');
  
  const [carrinho, setCarrinho] = useState<ItemCarrinho[]>(() => {
    try {
      const dadosSalvos = localStorage.getItem(CONFIG.STORAGE.CART_KEY);
      return dadosSalvos ? JSON.parse(dadosSalvos) : [];
    } catch (error) {
      console.error("Erro ao carregar localStorage:", error);
      return [];
    }
  });

  useEffect(() => {
    if (!usuario) return;

    const buscarProdutos = async () => {
      try {
        setIsCarregando(true);
        const apiUrl = import.meta.env.VITE_API_URL;
        // Fazemos o GET. O 404 deve sumir agora que registramos no server.ts
        const response = await axios.get<Produto[]>(`${apiUrl}/produtos`);
        
        if (response.data) {
          setProdutos(response.data);
        }
      } catch (err) {
        console.error("Erro ao carregar produtos:", err);
        toast.error("Não foi possível carregar o cardápio.");
      } finally {
        setIsCarregando(false);
      }
    };

    buscarProdutos();
  }, [usuario]);

  const categorias = useMemo(() => {
    return ['Todos', ...new Set(produtos.map(p => p.categoria))];
  }, [produtos]);

  const totalItens = useMemo(() => {
    return carrinho.reduce((acc, item) => acc + item.quantidade, 0);
  }, [carrinho]);

  const produtosFiltrados = useMemo(() => {
    return categoriaAtiva === 'Todos' 
      ? produtos 
      : produtos.filter(p => p.categoria === categoriaAtiva);
  }, [categoriaAtiva, produtos]);
  
  useEffect(() => {
    localStorage.setItem(CONFIG.STORAGE.CART_KEY, JSON.stringify(carrinho));
  }, [carrinho]);

  const handleSucessoLogin = (userData: UsuarioLogado) => {
    setUsuario(userData);
    localStorage.setItem('@CozinhaRamos:usuario', JSON.stringify(userData));
    toast.success(`Bem-vindo, ${userData.nome}!`);
  };

  const handleSair = () => {
    setUsuario(null);
    localStorage.removeItem('@CozinhaRamos:usuario');
    toast.success("Sessão encerrada!");
  };

  const adicionarAoCarrinho = (produto: Produto) => {
    setCarrinho(prev => {
      const itemExiste = prev.find(item => item.id === produto.id);
      if (itemExiste) {
        return prev.map(item => 
          item.id === produto.id ? { ...item, quantidade: item.quantidade + 1 } : item
        );
      }
      return [...prev, { ...produto, quantidade: 1 }];
    });

    toast.success(`${produto.nome} adicionado!`);
  };

  const removerDoCarrinho = (id: string) => {
    setCarrinho(prev => prev.filter(item => item.id !== id));
  };

  const atualizarQuantidade = (id: string, delta: number) => {
    setCarrinho(prev => {
      return prev
        .map(item => {
          if (item.id === id) {
            const novaQtd = item.quantidade + delta;
            return novaQtd > 0 ? { ...item, quantidade: novaQtd } : null;
          }
          return item;
        })
        .filter((item): item is ItemCarrinho => item !== null);
    });
  };

  const limparCarrinho = () => {
    setCarrinho([]);
    setIsCarrinhoAberto(false);
  };

  if (!usuario) {
    return (
      <div className="min-h-screen bg-[#FDF8F0] py-20">
        <Toaster />
        <div className="text-center mb-8">
           <h1 className="text-4xl font-bold text-[#435B17]">Cozinha Ramos</h1>
        </div>
        <Login onLoginSuccess={handleSucessoLogin} />
      </div>
    );
  }

  return (
    <div className="app-wrapper">
      <Header 
        quantidadeCarrinho={totalItens} 
        onCarrinhoAberto={() => setIsCarrinhoAberto(true)}
        onSair={handleSair}
        usuarioNome={usuario?.nome} 
      />

      <Toaster />
      
      <section className="hero-banner">
        <h2 className="hero-title">{CONFIG.APP.NAME}</h2>
        <p className="hero-subtitle">{CONFIG.APP.SLOGAN}</p>
      </section>

      <main className="main-content">
        <div className="filter-container">
          {categorias.map(cat => (
            <button
              key={cat}
              onClick={() => setCategoriaAtiva(cat)}
              className={`btn-filter ${categoriaAtiva === cat ? 'btn-filter-active' : 'btn-filter-inactive'}`}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="section-header">
          <h3 className="section-title">Nosso Cardápio</h3>
          <span className="delivery-badge">ENTREGA</span>
        </div>

        <div className="product-grid">
          {isCarregando ? (
            Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="skeleton skeleton-card" />
            ))
          ) : produtosFiltrados.length > 0 ? (
            produtosFiltrados.map(produto => (
              <CardProduto 
                key={produto.id} 
                produto={produto} 
                onAdd={adicionarAoCarrinho} 
              />
            ))
          ) : (
            <div className="empty-state">
              <p>Nenhum produto disponível no momento.</p>
            </div>
          )}
        </div>
      </main>

      <Footer />

      {isCarrinhoAberto && (
        <CarrinhoModal 
          itens={carrinho} 
          usuario={usuario}
          onFechar={() => setIsCarrinhoAberto(false)}
          onRemover={removerDoCarrinho}
          onAtualizarQtd={atualizarQuantidade}
          onFinalizar={limparCarrinho}
        />
      )}
    </div>
  );
}
